import {
  Utensils,
  ShoppingCart,
  Fuel,
  Bus,
  Car,
  Home,
  Zap,
  Droplet,
  Wifi,
  Phone,
  HeartPulse,
  GraduationCap,
  Gamepad2,
  ShoppingBag,
  Repeat,
  Wrench,
  Gem,
  PawPrint,
  Landmark,
  Percent,
  MoreHorizontal,
  Wallet,
  PlusCircle,
  Laptop,
  TrendingUp,
  Undo2,
  Circle,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  fuel: Fuel,
  bus: Bus,
  car: Car,
  home: Home,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  phone: Phone,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  "gamepad-2": Gamepad2,
  "shopping-bag": ShoppingBag,
  repeat: Repeat,
  wrench: Wrench,
  gem: Gem,
  "paw-print": PawPrint,
  landmark: Landmark,
  percent: Percent,
  "more-horizontal": MoreHorizontal,
  wallet: Wallet,
  "plus-circle": PlusCircle,
  laptop: Laptop,
  "trending-up": TrendingUp,
  "undo-2": Undo2,
};

export function CategoryIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = ICON_MAP[icon] ?? Circle;
  return <Icon className={className} strokeWidth={2} />;
}
